all:
	@cat makefile
watch:
	npm run watch
ui:
	vue ui
test:
	npm run test
selenium:
	npm run selenium-test
link:
	npm link vue-selenium-unittest
	npm link mongodb-simple-query-syntax
	npm link ac-input
